// Obstacle word lists — order matches THEMES in PlayScene.js (indexed by obstacleIndex)
// Difficulty groups: levels 0-1 = 3 letters, 2-4 = 4 letters, 5-7 = 5 letters,
//                   8-10 = 6 letters, 11-13 = 7 letters
export const OBSTACLES = [
  // ── 3-letter words ──────────────────────────────────────────────────────────
  {
    name: 'tree',
    emoji: '🌳',
    words: [
      { word: 'cat', emoji: '🐱', emojis: ['🐱', '😸', '🐈'] },
      { word: 'dog', emoji: '🐶', emojis: ['🐶', '🐕', '🦮'] },
      { word: 'hat', emoji: '🎩', emojis: ['🎩', '👒', '🪖'] },
      { word: 'sun', emoji: '☀️', emojis: ['☀️', '🌞', '🌅'] },
      { word: 'run', emoji: '🏃', emojis: ['🏃', '🏇'] },
      { word: 'ant', emoji: '🐜' },
      { word: 'cup', emoji: '☕', emojis: ['☕', '🍵', '🥤', '🫖'] },
      { word: 'egg', emoji: '🥚', emojis: ['🥚', '🍳'] },
      { word: 'pig', emoji: '🐷', emojis: ['🐷', '🐖'] },
      { word: 'hen', emoji: '🐔', emojis: ['🐔', '🐓'] },
      { word: 'owl', emoji: '🦉' },
      { word: 'bee', emoji: '🐝', emojis: ['🐝', '🍯'] },
      { word: 'bat', emoji: '🦇', emojis: ['🦇', '⚾', '🏏'] },
      { word: 'fox', emoji: '🦊' },
      { word: 'bug', emoji: '🐛', emojis: ['🐛', '🐞', '🦗'] },
      { word: 'bus', emoji: '🚌', emojis: ['🚌', '🚍'] },
      { word: 'box', emoji: '📦', emojis: ['📦', '🎁'] },
      { word: 'bed', emoji: '🛏️', emojis: ['🛏️', '😴'] },
      { word: 'hot', emoji: '🔥', emojis: ['🔥', '🌡️'] },
      { word: 'ice', emoji: '🧊', emojis: ['🧊', '❄️'] },
      { word: 'sky', emoji: '🌤️', emojis: ['🌤️', '☁️', '🌈', '🌙'] },
      { word: 'sea', emoji: '🌊', emojis: ['🌊', '🏖️', '⛵'] },
      { word: 'red', emoji: '🍎', emojis: ['🍎', '❤️', '🌹'] },
      { word: 'big', emoji: '🐘', emojis: ['🐘', '🦛', '🏔️'] },
      { word: 'wet', emoji: '💧', emojis: ['💧', '🌧️'] },
      { word: 'map', emoji: '🗺️', emojis: ['🗺️', '📍', '🧭'] },
      { word: 'toy', emoji: '🪀', emojis: ['🪀', '🧸', '🎮'] },
      { word: 'arm', emoji: '💪', emojis: ['💪', '🦾'] },
      { word: 'ear', emoji: '👂', emojis: ['👂', '🎧'] },
      { word: 'net', emoji: '🥅', emojis: ['🥅', '🕸️', '🏸'] },
      { word: 'jam', emoji: '🍓', emojis: ['🍓', '🍇', '🫙'] },
      { word: 'ram', emoji: '🐏', emojis: ['🐏', '🦌'] },
      { word: 'vet', emoji: '💉', emojis: ['💉', '🏥', '🐾'] },
      { word: 'zip', emoji: '⚡', emojis: ['⚡', '🤐', '💨'] },
      { word: 'web', emoji: '🕸️', emojis: ['🕸️', '🕷️'] },
      { word: 'nap', emoji: '😴', emojis: ['😴', '🛏️'] },
      { word: 'dip', emoji: '🌊', emojis: ['🌊', '🏊'] },
      { word: 'tub', emoji: '🛁', emojis: ['🛁', '🧼', '🫧'] },
      { word: 'mug', emoji: '☕', emojis: ['☕', '🫖', '🍵'] },
      { word: 'cub', emoji: '🐻', emojis: ['🐻', '🐼', '🦁'] },
      { word: 'gum', emoji: '🍬', emojis: ['🍬', '🦷'] },
      { word: 'fin', emoji: '🐟', emojis: ['🐟', '🦈'] },
      { word: 'win', emoji: '🏆', emojis: ['🏆', '🥇', '🎉'] },
      { word: 'van', emoji: '🚐', emojis: ['🚐', '🚌'] },
      { word: 'yak', emoji: '🦬', emojis: ['🦬', '🐂'] },
      { word: 'lip', emoji: '👄', emojis: ['👄', '💋'] },
      { word: 'sit', emoji: '🪑', emojis: ['🪑', '🧘'] },
      { word: 'mat', emoji: '🧘', emojis: ['🧘', '🛏️'] },
      { word: 'sip', emoji: '🥤', emojis: ['🥤', '☕', '🍵'] },
      { word: 'hay', emoji: '🌾', emojis: ['🌾', '🐴'] },
    ],
  },
  {
    name: 'mountain',
    emoji: '⛰️',
    words: [
      { word: 'air', emoji: '💨', emojis: ['💨', '🌬️', '🍃'] },
      { word: 'bow', emoji: '🏹', emojis: ['🏹', '🎀', '🎻'] },
      { word: 'can', emoji: '🥫', emojis: ['🥫', '🗑️'] },
      { word: 'car', emoji: '🚗', emojis: ['🚗', '🚙', '🏎️'] },
      { word: 'cow', emoji: '🐄', emojis: ['🐄', '🐮'] },
      { word: 'cry', emoji: '😢', emojis: ['😢', '😭', '💧'] },
      { word: 'cut', emoji: '✂️', emojis: ['✂️', '🔪'] },
      { word: 'day', emoji: '🌅', emojis: ['🌅', '☀️', '🌤️'] },
      { word: 'dry', emoji: '☀️', emojis: ['☀️', '🏜️'] },
      { word: 'eye', emoji: '👁️', emojis: ['👁️', '👀'] },
      { word: 'fan', emoji: '🌀', emojis: ['🌀', '🪭', '❤️‍🔥'] },
      { word: 'fly', emoji: '🦋', emojis: ['🦋', '✈️', '🪰'] },
      { word: 'fun', emoji: '🎉', emojis: ['🎉', '🎊', '😄'] },
      { word: 'hop', emoji: '🐰', emojis: ['🐰', '🐸', '🦘'] },
      { word: 'hug', emoji: '🤗', emojis: ['🤗', '🫂'] },
      { word: 'jug', emoji: '🫙', emojis: ['🫙', '🍶', '🪣'] },
      { word: 'key', emoji: '🔑', emojis: ['🔑', '🗝️'] },
      { word: 'leg', emoji: '🦵', emojis: ['🦵', '🏃'] },
      { word: 'log', emoji: '🪵', emojis: ['🪵', '🌲', '🔥'] },
      { word: 'mud', emoji: '💧', emojis: ['💧', '🏺', '🟤'] },
      { word: 'nut', emoji: '🥜', emojis: ['🥜', '🌰'] },
      { word: 'oak', emoji: '🌲', emojis: ['🌲', '🌳', '🌿'] },
      { word: 'pan', emoji: '🍳', emojis: ['🍳', '🥘'] },
      { word: 'pen', emoji: '✏️', emojis: ['✏️', '🖊️', '🖋️'] },
      { word: 'pie', emoji: '🥧', emojis: ['🥧', '🍰'] },
      { word: 'pop', emoji: '🎈', emojis: ['🎈', '💥', '🍿'] },
      { word: 'pup', emoji: '🐶', emojis: ['🐶', '🐕'] },
      { word: 'row', emoji: '🚣', emojis: ['🚣', '🛶'] },
      { word: 'tug', emoji: '💪', emojis: ['💪', '⚓'] },
      { word: 'zoo', emoji: '🦁', emojis: ['🦁', '🐘', '🦒', '🐧'] },
      { word: 'rat', emoji: '🐀', emojis: ['🐀', '🐭'] },
      { word: 'pot', emoji: '🍯', emojis: ['🍯', '🌱', '🫙'] },
      { word: 'dot', emoji: '⚫', emojis: ['⚫', '🎯', '⭕'] },
      { word: 'tip', emoji: '💡', emojis: ['💡', '💰', '☝️'] },
      { word: 'joy', emoji: '😊', emojis: ['😊', '🎉', '😄'] },
      { word: 'bay', emoji: '🌊', emojis: ['🌊', '🏖️', '⛵'] },
      { word: 'ray', emoji: '☀️', emojis: ['☀️', '🌈'] },
      { word: 'dew', emoji: '💧', emojis: ['💧', '🌿', '🌅'] },
      { word: 'ivy', emoji: '🌿', emojis: ['🌿', '🍃', '🪴'] },
      { word: 'jet', emoji: '✈️', emojis: ['✈️', '🚀', '💨'] },
      { word: 'lab', emoji: '🔬', emojis: ['🔬', '🧪'] },
      { word: 'lap', emoji: '🐕', emojis: ['🐕', '🐱', '🪑'] },
      { word: 'pet', emoji: '🐾', emojis: ['🐾', '🐕', '🐱'] },
      { word: 'pit', emoji: '🕳️', emojis: ['🕳️', '⚾'] },
      { word: 'sob', emoji: '😭', emojis: ['😭', '💧', '😢'] },
      { word: 'son', emoji: '👦', emojis: ['👦', '☀️'] },
      { word: 'tan', emoji: '🏖️', emojis: ['🏖️', '🌅', '🟤'] },
      { word: 'tap', emoji: '🚰', emojis: ['🚰', '🎵', '👆'] },
      { word: 'wok', emoji: '🍳', emojis: ['🍳', '🥘'] },
      { word: 'yam', emoji: '🍠', emojis: ['🍠', '🟠'] },
    ],
  },
  // ── 4-letter words ──────────────────────────────────────────────────────────
  {
    name: 'snowy mountain',
    emoji: '❄️',
    words: [
      { word: 'snow', emoji: '❄️', emojis: ['❄️', '⛄', '🌨️'] },
      { word: 'cold', emoji: '🥶', emojis: ['🥶', '❄️'] },
      { word: 'wind', emoji: '💨', emojis: ['💨', '🌬️'] },
      { word: 'coat', emoji: '🧥', emojis: ['🧥', '🧣'] },
      { word: 'wool', emoji: '🐑', emojis: ['🐑', '🧶'] },
      { word: 'sled', emoji: '🛷', emojis: ['🛷', '⛷️'] },
      { word: 'boot', emoji: '👢', emojis: ['👢', '🥾'] },
      { word: 'pine', emoji: '🌲', emojis: ['🌲', '🎄'] },
      { word: 'hawk', emoji: '🦅', emojis: ['🦅', '🐦'] },
      { word: 'deer', emoji: '🦌', emojis: ['🦌', '🦙'] },
      { word: 'wolf', emoji: '🐺', emojis: ['🐺', '🐕'] },
      { word: 'rock', emoji: '🪨', emojis: ['🪨', '⛰️'] },
      { word: 'cave', emoji: '🕳️', emojis: ['🕳️', '🏔️'] },
      { word: 'path', emoji: '🛤️', emojis: ['🛤️', '🗺️', '👣'] },
      { word: 'crow', emoji: '🐦', emojis: ['🐦', '🐧'] },
      { word: 'peak', emoji: '🏔️', emojis: ['🏔️', '⛰️'] },
      { word: 'gray', emoji: '☁️', emojis: ['☁️', '🌫️', '🐘'] },
      { word: 'hill', emoji: '⛰️', emojis: ['⛰️', '🏔️'] },
      { word: 'fern', emoji: '🌿', emojis: ['🌿', '🍃'] },
      { word: 'melt', emoji: '💧', emojis: ['💧', '☀️'] },
      { word: 'glow', emoji: '✨', emojis: ['✨', '💡', '🌟'] },
      { word: 'beam', emoji: '🔦', emojis: ['🔦', '☀️', '💡'] },
      { word: 'nest', emoji: '🪺', emojis: ['🪺', '🐦'] },
      { word: 'pale', emoji: '🌫️', emojis: ['🌫️', '⬜'] },
      { word: 'wild', emoji: '🌿', emojis: ['🌿', '🐺', '🦌'] },
      { word: 'tall', emoji: '⛰️', emojis: ['⛰️', '🌲', '🦒'] },
      { word: 'thin', emoji: '❄️', emojis: ['❄️', '🌾'] },
      { word: 'deep', emoji: '🌊', emojis: ['🌊', '🕳️', '🏔️'] },
      { word: 'mist', emoji: '🌫️', emojis: ['🌫️', '☁️'] },
      { word: 'hail', emoji: '🌨️', emojis: ['🌨️', '⛈️'] },
      { word: 'slip', emoji: '🧊', emojis: ['🧊', '💦'] },
      { word: 'drip', emoji: '💧', emojis: ['💧', '🌧️'] },
      { word: 'grip', emoji: '✋', emojis: ['✋', '💪'] },
      { word: 'chip', emoji: '🪨', emojis: ['🪨', '🍟'] },
      { word: 'flip', emoji: '🔄', emojis: ['🔄', '🤸'] },
      { word: 'cozy', emoji: '🛋️', emojis: ['🛋️', '🧣', '☕'] },
      { word: 'rime', emoji: '❄️', emojis: ['❄️', '🌫️'] },
      { word: 'crag', emoji: '🏔️', emojis: ['🏔️', '🪨'] },
      { word: 'dusk', emoji: '🌆', emojis: ['🌆', '🌅', '🌙'] },
      { word: 'fawn', emoji: '🦌', emojis: ['🦌', '🐾'] },
      { word: 'gale', emoji: '💨', emojis: ['💨', '🌬️', '⛈️'] },
      { word: 'howl', emoji: '🐺', emojis: ['🐺', '🌕', '💨'] },
      { word: 'limp', emoji: '🦵', emojis: ['🦵', '🩹'] },
      { word: 'plow', emoji: '🚜', emojis: ['🚜', '❄️'] },
      { word: 'rust', emoji: '🟤', emojis: ['🟤', '⚙️'] },
      { word: 'snap', emoji: '📸', emojis: ['📸', '💥', '🫰'] },
      { word: 'snug', emoji: '🤗', emojis: ['🤗', '🛋️'] },
      { word: 'soak', emoji: '💧', emojis: ['💧', '🛁'] },
      { word: 'soap', emoji: '🧼', emojis: ['🧼', '🫧'] },
      { word: 'lark', emoji: '🐦', emojis: ['🐦', '🎵'] },
    ],
  },
  {
    name: 'volcano',
    emoji: '🌋',
    words: [
      { word: 'bear', emoji: '🐻', emojis: ['🐻', '🐨', '🐼'] },
      { word: 'frog', emoji: '🐸' },
      { word: 'fish', emoji: '🐟', emojis: ['🐟', '🐠', '🐡', '🦈'] },
      { word: 'duck', emoji: '🦆', emojis: ['🦆', '🐥'] },
      { word: 'bird', emoji: '🐦', emojis: ['🐦', '🦜', '🦚', '🦅'] },
      { word: 'tree', emoji: '🌳', emojis: ['🌳', '🌲', '🌴'] },
      { word: 'rain', emoji: '🌧️', emojis: ['🌧️', '☔', '💧'] },
      { word: 'star', emoji: '⭐', emojis: ['⭐', '🌟', '✨', '💫'] },
      { word: 'moon', emoji: '🌙', emojis: ['🌙', '🌕', '🌛'] },
      { word: 'cake', emoji: '🎂', emojis: ['🎂', '🍰', '🧁'] },
      { word: 'milk', emoji: '🥛', emojis: ['🥛', '🍼'] },
      { word: 'ball', emoji: '⚽', emojis: ['⚽', '🏀', '🎾', '⚾'] },
      { word: 'book', emoji: '📚', emojis: ['📚', '📖', '📕'] },
      { word: 'rose', emoji: '🌹', emojis: ['🌹', '🌸', '💐'] },
      { word: 'boat', emoji: '⛵', emojis: ['⛵', '🚤', '🛶'] },
      { word: 'kite', emoji: '🪁', emojis: ['🪁', '🎏'] },
      { word: 'drum', emoji: '🥁', emojis: ['🥁', '🎵'] },
      { word: 'bell', emoji: '🔔', emojis: ['🔔', '🎵', '🔕'] },
      { word: 'leaf', emoji: '🍂', emojis: ['🍂', '🍃', '🌿'] },
      { word: 'corn', emoji: '🌽' },
      { word: 'farm', emoji: '🚜', emojis: ['🚜', '🌾', '🐄'] },
      { word: 'lake', emoji: '🏞️', emojis: ['🏞️', '🌊', '⛵'] },
      { word: 'hand', emoji: '✋', emojis: ['✋', '👋', '🤚'] },
      { word: 'song', emoji: '🎵', emojis: ['🎵', '🎶', '🎤'] },
      { word: 'blue', emoji: '💙', emojis: ['💙', '🫐', '🌊', '🦋'] },
      { word: 'jump', emoji: '🐸', emojis: ['🐸', '🦘', '🏃'] },
      { word: 'open', emoji: '🚪', emojis: ['🚪', '📬'] },
      { word: 'worm', emoji: '🪱', emojis: ['🪱', '🐛'] },
      { word: 'buzz', emoji: '🐝', emojis: ['🐝', '📳', '🔔'] },
      { word: 'toad', emoji: '🐸', emojis: ['🐸', '🐊'] },
      { word: 'bake', emoji: '🍞', emojis: ['🍞', '🧁', '🍰'] },
      { word: 'clay', emoji: '🏺', emojis: ['🏺', '🎨'] },
      { word: 'coal', emoji: '🪨', emojis: ['🪨', '🔥', '🟤'] },
      { word: 'dark', emoji: '🌑', emojis: ['🌑', '🌙', '🕯️'] },
      { word: 'dash', emoji: '💨', emojis: ['💨', '🏃', '⚡'] },
      { word: 'flap', emoji: '🦋', emojis: ['🦋', '🐦', '🪁'] },
      { word: 'gush', emoji: '💦', emojis: ['💦', '🌊'] },
      { word: 'heat', emoji: '🌡️', emojis: ['🌡️', '🔥', '☀️'] },
      { word: 'hive', emoji: '🐝', emojis: ['🐝', '🍯'] },
      { word: 'knot', emoji: '⛵', emojis: ['⛵', '🎀', '🪢'] },
      { word: 'lava', emoji: '🌋', emojis: ['🌋', '🔥', '🟠'] },
      { word: 'lick', emoji: '👅', emojis: ['👅', '🍦', '🐕'] },
      { word: 'lift', emoji: '💪', emojis: ['💪', '🏋️', '🚀'] },
      { word: 'mash', emoji: '🥔', emojis: ['🥔', '🍲'] },
      { word: 'newt', emoji: '🦎', emojis: ['🦎', '🐊'] },
      { word: 'plop', emoji: '💧', emojis: ['💧', '🐸'] },
      { word: 'wick', emoji: '🕯️', emojis: ['🕯️', '🔥'] },
      { word: 'yell', emoji: '📢', emojis: ['📢', '😠', '🗣️'] },
      { word: 'zoom', emoji: '💨', emojis: ['💨', '🚀', '🏎️'] },
      { word: 'glow', emoji: '✨', emojis: ['✨', '💡', '🌟', '🕯️'] },
    ],
  },
  {
    name: 'reef',
    emoji: '🪸',
    words: [
      { word: 'reef', emoji: '🪸' },
      { word: 'crab', emoji: '🦀' },
      { word: 'kelp', emoji: '🌿', emojis: ['🌿', '🍃'] },
      { word: 'dive', emoji: '🤿', emojis: ['🤿', '🏊'] },
      { word: 'tide', emoji: '🌊', emojis: ['🌊', '🌙'] },
      { word: 'wave', emoji: '🌊', emojis: ['🌊', '👋', '🏄'] },
      { word: 'clam', emoji: '🦪', emojis: ['🦪', '🐚'] },
      { word: 'seal', emoji: '🦭', emojis: ['🦭', '🐟'] },
      { word: 'sand', emoji: '🏖️', emojis: ['🏖️', '🏜️', '⏳'] },
      { word: 'swim', emoji: '🏊', emojis: ['🏊', '🤿', '🦈'] },
      { word: 'warm', emoji: '☀️', emojis: ['☀️', '🌡️', '🔥'] },
      { word: 'salt', emoji: '🧂' },
      { word: 'pool', emoji: '🏊', emojis: ['🏊', '🌊', '🐟'] },
      { word: 'gill', emoji: '🐟', emojis: ['🐟', '🐠'] },
      { word: 'tail', emoji: '🐠', emojis: ['🐠', '🦊', '🐟'] },
      { word: 'foam', emoji: '🌊', emojis: ['🌊', '🧼', '🫧'] },
      { word: 'cove', emoji: '🏝️', emojis: ['🏝️', '⛵', '🌊'] },
      { word: 'weed', emoji: '🌿', emojis: ['🌿', '🍃'] },
      { word: 'cool', emoji: '🧊', emojis: ['🧊', '❄️', '😎'] },
      { word: 'damp', emoji: '💧', emojis: ['💧', '🌧️'] },
      { word: 'dark', emoji: '🌑', emojis: ['🌑', '🕳️'] },
      { word: 'raft', emoji: '🛶', emojis: ['🛶', '🌊'] },
      { word: 'wade', emoji: '🌊', emojis: ['🌊', '🏖️'] },
      { word: 'teal', emoji: '🩵', emojis: ['🩵', '🌊', '🦆'] },
      { word: 'puff', emoji: '🐡', emojis: ['🐡', '💨', '☁️'] },
      { word: 'buoy', emoji: '🛟', emojis: ['🛟', '⚓'] },
      { word: 'fins', emoji: '🤿', emojis: ['🤿', '🐟', '🦈'] },
      { word: 'rays', emoji: '☀️', emojis: ['☀️', '🌈', '🐟'] },
      { word: 'gust', emoji: '💨', emojis: ['💨', '🌬️'] },
      { word: 'mast', emoji: '⛵', emojis: ['⛵', '🏴‍☠️'] },
      { word: 'brim', emoji: '🎩', emojis: ['🎩', '🫙'] },
      { word: 'calm', emoji: '😌', emojis: ['😌', '🌊', '☁️'] },
      { word: 'cast', emoji: '🎣', emojis: ['🎣', '🎭'] },
      { word: 'clip', emoji: '📎', emojis: ['📎', '✂️'] },
      { word: 'crew', emoji: '⚓', emojis: ['⚓', '🧑‍✈️'] },
      { word: 'curl', emoji: '🌊', emojis: ['🌊', '💇', '🌀'] },
      { word: 'dock', emoji: '⚓', emojis: ['⚓', '🛳️', '🐟'] },
      { word: 'dune', emoji: '🏖️', emojis: ['🏖️', '🏜️'] },
      { word: 'hull', emoji: '⛵', emojis: ['⛵', '🛳️'] },
      { word: 'isle', emoji: '🏝️', emojis: ['🏝️', '🌴', '🌊'] },
      { word: 'keel', emoji: '⛵', emojis: ['⛵', '⚓'] },
      { word: 'oar', emoji: '🚣', emojis: ['🚣', '🛶'] },
      { word: 'pier', emoji: '🌊', emojis: ['🌊', '⚓', '🎣'] },
      { word: 'reel', emoji: '🎣', emojis: ['🎣', '🎬'] },
      { word: 'rope', emoji: '🪢', emojis: ['🪢', '⛵'] },
      { word: 'seep', emoji: '💧', emojis: ['💧', '🌿'] },
      { word: 'surf', emoji: '🏄', emojis: ['🏄', '🌊'] },
      { word: 'skid', emoji: '💦', emojis: ['💦', '🚗'] },
      { word: 'slap', emoji: '👋', emojis: ['👋', '🌊'] },
      { word: 'snip', emoji: '✂️', emojis: ['✂️', '🐟'] },
    ],
  },
  // ── 5-letter words ──────────────────────────────────────────────────────────
  {
    name: 'jungle',
    emoji: '🌴',
    words: [
      { word: 'apple', emoji: '🍎', emojis: ['🍎', '🍏'] },
      { word: 'cloud', emoji: '☁️', emojis: ['☁️', '⛅', '🌧️'] },
      { word: 'dance', emoji: '💃', emojis: ['💃', '🕺', '🎵'] },
      { word: 'earth', emoji: '🌍', emojis: ['🌍', '🌎', '🌏'] },
      { word: 'flame', emoji: '🔥', emojis: ['🔥', '🕯️', '🌋'] },
      { word: 'grape', emoji: '🍇', emojis: ['🍇', '🍷'] },
      { word: 'happy', emoji: '😊', emojis: ['😊', '😄', '🎉', '😁'] },
      { word: 'juice', emoji: '🍹', emojis: ['🍹', '🧃', '🍊'] },
      { word: 'lemon', emoji: '🍋', emojis: ['🍋', '🟡'] },
      { word: 'music', emoji: '🎵', emojis: ['🎵', '🎶', '🎸'] },
      { word: 'night', emoji: '🌙', emojis: ['🌙', '🌑', '⭐'] },
      { word: 'ocean', emoji: '🌊', emojis: ['🌊', '🐋', '🏖️'] },
      { word: 'plant', emoji: '🌱', emojis: ['🌱', '🌿', '🪴'] },
      { word: 'queen', emoji: '👸', emojis: ['👸', '👑'] },
      { word: 'river', emoji: '🌊', emojis: ['🌊', '🚣', '🐟'] },
      { word: 'sheep', emoji: '🐑', emojis: ['🐑', '🐏', '🧶'] },
      { word: 'tiger', emoji: '🐯', emojis: ['🐯', '🐅'] },
      { word: 'whale', emoji: '🐋', emojis: ['🐋', '🐳'] },
      { word: 'zebra', emoji: '🦓' },
      { word: 'bread', emoji: '🍞', emojis: ['🍞', '🥖', '🥐'] },
      { word: 'crown', emoji: '👑', emojis: ['👑', '🎪'] },
      { word: 'heart', emoji: '❤️', emojis: ['❤️', '💕', '🩷', '💝'] },
      { word: 'igloo', emoji: '🏠', emojis: ['🏠', '❄️', '⛄'] },
      { word: 'koala', emoji: '🐨' },
      { word: 'light', emoji: '💡', emojis: ['💡', '🔦', '🕯️', '☀️'] },
      { word: 'mango', emoji: '🥭', emojis: ['🥭', '🍊'] },
      { word: 'panda', emoji: '🐼' },
      { word: 'pizza', emoji: '🍕' },
      { word: 'robot', emoji: '🤖' },
      { word: 'flute', emoji: '🪈', emojis: ['🪈', '🎵'] },
      { word: 'amber', emoji: '🟡', emojis: ['🟡', '🌅', '🍯'] },
      { word: 'birch', emoji: '🌲', emojis: ['🌲', '🍃'] },
      { word: 'bloom', emoji: '🌸', emojis: ['🌸', '🌺', '🌻'] },
      { word: 'cabin', emoji: '🏠', emojis: ['🏠', '🌲', '🏕️'] },
      { word: 'chalk', emoji: '✏️', emojis: ['✏️', '⬜', '🎨'] },
      { word: 'chess', emoji: '♟️', emojis: ['♟️', '🎯'] },
      { word: 'chick', emoji: '🐣', emojis: ['🐣', '🐥'] },
      { word: 'crisp', emoji: '🍃', emojis: ['🍃', '❄️', '🍟'] },
      { word: 'daisy', emoji: '🌼', emojis: ['🌼', '🌸'] },
      { word: 'fancy', emoji: '✨', emojis: ['✨', '👗', '💎'] },
      { word: 'feast', emoji: '🍽️', emojis: ['🍽️', '🦃', '🎉'] },
      { word: 'field', emoji: '🌾', emojis: ['🌾', '🐄', '⚽'] },
      { word: 'frost', emoji: '❄️', emojis: ['❄️', '🌫️', '🥶'] },
      { word: 'gleam', emoji: '✨', emojis: ['✨', '💡', '🌟'] },
      { word: 'herbs', emoji: '🌿', emojis: ['🌿', '🍃', '🌱'] },
      { word: 'honey', emoji: '🍯', emojis: ['🍯', '🐝', '🍬'] },
      { word: 'lucky', emoji: '🍀', emojis: ['🍀', '🌟', '🎲'] },
      { word: 'magic', emoji: '✨', emojis: ['✨', '🔮', '🪄'] },
      { word: 'stern', emoji: '⛵', emojis: ['⛵', '😠'] },
      { word: 'storm', emoji: '⛈️', emojis: ['⛈️', '🌩️', '🌪️'] },
    ],
  },
  {
    name: 'underwater',
    emoji: '🌊',
    words: [
      { word: 'coral', emoji: '🪸', emojis: ['🪸', '🌺'] },
      { word: 'shark', emoji: '🦈' },
      { word: 'squid', emoji: '🦑' },
      { word: 'otter', emoji: '🦦' },
      { word: 'prawn', emoji: '🦐' },
      { word: 'snail', emoji: '🐌', emojis: ['🐌', '🐚'] },
      { word: 'trout', emoji: '🐟', emojis: ['🐟', '🐠'] },
      { word: 'algae', emoji: '🌿', emojis: ['🌿', '🍃'] },
      { word: 'salty', emoji: '🧂', emojis: ['🧂', '🌊'] },
      { word: 'water', emoji: '💧', emojis: ['💧', '🌊', '🚰'] },
      { word: 'pearl', emoji: '⚪', emojis: ['⚪', '🐚', '💎'] },
      { word: 'shell', emoji: '🐚', emojis: ['🐚', '⚪', '🦪'] },
      { word: 'storm', emoji: '🌪️', emojis: ['🌪️', '⛈️', '🌊'] },
      { word: 'brave', emoji: '🦸', emojis: ['🦸', '💪', '🛡️'] },
      { word: 'float', emoji: '🌊', emojis: ['🌊', '🎈', '🛟'] },
      { word: 'sunny', emoji: '☀️', emojis: ['☀️', '🌞', '🌅'] },
      { word: 'puppy', emoji: '🐶', emojis: ['🐶', '🐕', '🦮'] },
      { word: 'kitty', emoji: '🐱', emojis: ['🐱', '😸', '🐈'] },
      { word: 'bunny', emoji: '🐰', emojis: ['🐰', '🐇'] },
      { word: 'candy', emoji: '🍬', emojis: ['🍬', '🍭', '🍫'] },
      { word: 'daisy', emoji: '🌼', emojis: ['🌼', '🌸'] },
      { word: 'lucky', emoji: '🍀', emojis: ['🍀', '🌟'] },
      { word: 'rainy', emoji: '🌧️', emojis: ['🌧️', '☔', '💧'] },
      { word: 'dizzy', emoji: '💫', emojis: ['💫', '🌀', '😵'] },
      { word: 'fuzzy', emoji: '🐻', emojis: ['🐻', '🧸', '🐑'] },
      { word: 'sandy', emoji: '🏖️', emojis: ['🏖️', '🏜️', '⏳'] },
      { word: 'bloom', emoji: '🌺', emojis: ['🌺', '🌸', '🌸'] },
      { word: 'fishy', emoji: '🐟', emojis: ['🐟', '🐠', '🐡'] },
      { word: 'rocky', emoji: '🪨', emojis: ['🪨', '⛰️'] },
      { word: 'brine', emoji: '🌊', emojis: ['🌊', '🧂'] },
      { word: 'azure', emoji: '🩵', emojis: ['🩵', '🌊', '☁️'] },
      { word: 'blaze', emoji: '🔥', emojis: ['🔥', '🌟', '⚡'] },
      { word: 'derby', emoji: '🏇', emojis: ['🏇', '🏆'] },
      { word: 'elbow', emoji: '🦵', emojis: ['🦵', '💪'] },
      { word: 'ember', emoji: '🔥', emojis: ['🔥', '✨', '🕯️'] },
      { word: 'fairy', emoji: '🧚', emojis: ['🧚', '✨', '🪄'] },
      { word: 'flare', emoji: '🔦', emojis: ['🔦', '🔥', '✨'] },
      { word: 'grace', emoji: '🕊️', emojis: ['🕊️', '✨', '🩰'] },
      { word: 'grove', emoji: '🌲', emojis: ['🌲', '🌳', '🌿'] },
      { word: 'habit', emoji: '📋', emojis: ['📋', '🔄'] },
      { word: 'hazel', emoji: '🌰', emojis: ['🌰', '🟤', '🌿'] },
      { word: 'heron', emoji: '🦢', emojis: ['🦢', '🐦'] },
      { word: 'hippo', emoji: '🦛', emojis: ['🦛', '🐘'] },
      { word: 'horse', emoji: '🐴', emojis: ['🐴', '🏇', '🦄'] },
      { word: 'lotus', emoji: '🪷', emojis: ['🪷', '🌸'] },
      { word: 'maple', emoji: '🍁', emojis: ['🍁', '🌳'] },
      { word: 'niece', emoji: '👧', emojis: ['👧', '👨‍👧'] },
      { word: 'olive', emoji: '🫒', emojis: ['🫒', '🌿'] },
      { word: 'crimp', emoji: '〰️', emojis: ['〰️', '🌊'] },
      { word: 'clamp', emoji: '🔧', emojis: ['🔧', '💪'] },
    ],
  },
  {
    name: 'cloud',
    emoji: '☁️',
    words: [
      { word: 'cloud', emoji: '☁️', emojis: ['☁️', '⛅', '🌧️'] },
      { word: 'light', emoji: '💡', emojis: ['💡', '🔦', '🕯️', '☀️'] },
      { word: 'rainy', emoji: '🌧️', emojis: ['🌧️', '☔', '💧'] },
      { word: 'foggy', emoji: '🌫️', emojis: ['🌫️', '☁️'] },
      { word: 'windy', emoji: '💨', emojis: ['💨', '🌬️', '🍃'] },
      { word: 'storm', emoji: '⛈️', emojis: ['⛈️', '🌩️', '🌪️'] },
      { word: 'drift', emoji: '🌊', emojis: ['🌊', '💨', '❄️'] },
      { word: 'misty', emoji: '🌫️', emojis: ['🌫️', '💧', '☁️'] },
      { word: 'sunny', emoji: '☀️', emojis: ['☀️', '🌞', '🌈'] },
      { word: 'above', emoji: '⬆️', emojis: ['⬆️', '☁️', '🚀'] },
      { word: 'float', emoji: '🎈', emojis: ['🎈', '🌊', '🛟'] },
      { word: 'glide', emoji: '🪁', emojis: ['🪁', '🦅', '✈️'] },
      { word: 'wispy', emoji: '🌫️', emojis: ['🌫️', '☁️', '🌿'] },
      { word: 'gusty', emoji: '💨', emojis: ['💨', '🌬️'] },
      { word: 'puffy', emoji: '☁️', emojis: ['☁️', '🐑', '💨'] },
      { word: 'fluff', emoji: '🐑', emojis: ['🐑', '☁️', '🧸'] },
      { word: 'crisp', emoji: '🍃', emojis: ['🍃', '❄️'] },
      { word: 'vapor', emoji: '💨', emojis: ['💨', '☁️', '🫧'] },
      { word: 'moist', emoji: '💧', emojis: ['💧', '🌿'] },
      { word: 'swirl', emoji: '🌀', emojis: ['🌀', '💨', '🌊'] },
      { word: 'frost', emoji: '❄️', emojis: ['❄️', '🌫️', '🥶'] },
      { word: 'patch', emoji: '🏔️', emojis: ['🏔️', '☁️', '🩹'] },
      { word: 'white', emoji: '⬜', emojis: ['⬜', '🤍', '☁️', '⛄'] },
      { word: 'layer', emoji: '🎂', emojis: ['🎂', '☁️', '📄'] },
      { word: 'sheet', emoji: '📄', emojis: ['📄', '🛏️', '⬜'] },
      { word: 'clear', emoji: '🔭', emojis: ['🔭', '☀️', '💎'] },
      { word: 'angel', emoji: '👼', emojis: ['👼', '😇', '✨'] },
      { word: 'shiny', emoji: '✨', emojis: ['✨', '💎', '🌟'] },
      { word: 'blowy', emoji: '💨', emojis: ['💨', '🌬️'] },
      { word: 'perch', emoji: '🐦', emojis: ['🐦', '🌲', '🎣'] },
      { word: 'blimp', emoji: '🎈', emojis: ['🎈', '☁️', '🛸'] },
      { word: 'bliss', emoji: '😌', emojis: ['😌', '✨', '😇'] },
      { word: 'brace', emoji: '💪', emojis: ['💪', '🛡️'] },
      { word: 'charm', emoji: '✨', emojis: ['✨', '🍀', '🪄'] },
      { word: 'cheek', emoji: '😊', emojis: ['😊', '🌹', '💋'] },
      { word: 'chewy', emoji: '🍬', emojis: ['🍬', '🍭', '🦷'] },
      { word: 'chief', emoji: '👑', emojis: ['👑', '🧢'] },
      { word: 'cleft', emoji: '🏔️', emojis: ['🏔️', '🪨'] },
      { word: 'cliff', emoji: '🏔️', emojis: ['🏔️', '🦅', '🪨'] },
      { word: 'cling', emoji: '🐒', emojis: ['🐒', '🧲', '🍃'] },
      { word: 'cloak', emoji: '🧙', emojis: ['🧙', '🌑', '🪄'] },
      { word: 'clown', emoji: '🤡', emojis: ['🤡', '🎪', '🎈'] },
      { word: 'crane', emoji: '🏗️', emojis: ['🏗️', '🦢', '🐦'] },
      { word: 'creak', emoji: '🚪', emojis: ['🚪', '🌲'] },
      { word: 'creed', emoji: '📜', emojis: ['📜', '⭐'] },
      { word: 'cross', emoji: '➕', emojis: ['➕', '😠', '🌈'] },
      { word: 'dwarf', emoji: '🧙', emojis: ['🧙', '⛏️', '🍄'] },
      { word: 'epoch', emoji: '⏳', emojis: ['⏳', '🕰️'] },
      { word: 'flair', emoji: '✨', emojis: ['✨', '💃', '🎨'] },
      { word: 'floss', emoji: '🦷', emojis: ['🦷', '🪥', '🩰'] },
    ],
  },
  // ── 6-letter words ──────────────────────────────────────────────────────────
  {
    name: 'olympus mons',
    emoji: '🔴',
    words: [
      { word: 'planet', emoji: '🌍', emojis: ['🌍', '🌎', '🌏', '🪐'] },
      { word: 'crater', emoji: '🌋', emojis: ['🌋', '⭕', '🔴'] },
      { word: 'canyon', emoji: '🏜️', emojis: ['🏜️', '🌄'] },
      { word: 'desert', emoji: '🏜️', emojis: ['🏜️', '🐪', '☀️'] },
      { word: 'launch', emoji: '🚀', emojis: ['🚀', '🛸', '🌋'] },
      { word: 'frozen', emoji: '❄️', emojis: ['❄️', '🥶', '🧊'] },
      { word: 'valley', emoji: '🏔️', emojis: ['🏔️', '🌄'] },
      { word: 'summit', emoji: '⛰️', emojis: ['⛰️', '🏔️', '🚩'] },
      { word: 'oxygen', emoji: '💨', emojis: ['💨', '🌬️', '🫁'] },
      { word: 'lander', emoji: '🛸', emojis: ['🛸', '🚀', '🌕'] },
      { word: 'rocket', emoji: '🚀', emojis: ['🚀', '🛸', '🔥'] },
      { word: 'garden', emoji: '🌻', emojis: ['🌻', '🌹', '🌿', '🐛'] },
      { word: 'hammer', emoji: '🔨', emojis: ['🔨', '🛠️'] },
      { word: 'castle', emoji: '🏰', emojis: ['🏰', '🏯', '♟️'] },
      { word: 'bridge', emoji: '🌉', emojis: ['🌉', '🏗️'] },
      { word: 'engine', emoji: '🚂', emojis: ['🚂', '⚙️', '🔧'] },
      { word: 'flower', emoji: '🌸', emojis: ['🌸', '🌼', '🌺', '🌻'] },
      { word: 'pencil', emoji: '✏️', emojis: ['✏️', '🖊️'] },
      { word: 'rabbit', emoji: '🐰', emojis: ['🐰', '🐇'] },
      { word: 'school', emoji: '🏫', emojis: ['🏫', '📚', '✏️'] },
      { word: 'turtle', emoji: '🐢' },
      { word: 'violin', emoji: '🎻', emojis: ['🎻', '🎵'] },
      { word: 'window', emoji: '🪟', emojis: ['🪟', '🏠'] },
      { word: 'butter', emoji: '🧈', emojis: ['🧈', '🍞'] },
      { word: 'candle', emoji: '🕯️', emojis: ['🕯️', '🔥', '✨'] },
      { word: 'finger', emoji: '👆', emojis: ['👆', '☝️', '🖐️'] },
      { word: 'giggle', emoji: '😂', emojis: ['😂', '😄', '🤭'] },
      { word: 'insect', emoji: '🐛', emojis: ['🐛', '🐝', '🦗', '🐞'] },
      { word: 'jigsaw', emoji: '🧩' },
      { word: 'muffin', emoji: '🧁', emojis: ['🧁', '🍰', '🥐'] },
      { word: 'action', emoji: '🎬', emojis: ['🎬', '🏃', '⚡'] },
      { word: 'animal', emoji: '🦁', emojis: ['🦁', '🐘', '🐒', '🦊'] },
      { word: 'basket', emoji: '🧺', emojis: ['🧺', '🏀', '🍓'] },
      { word: 'battle', emoji: '⚔️', emojis: ['⚔️', '🛡️'] },
      { word: 'beacon', emoji: '🔦', emojis: ['🔦', '🚨', '💡'] },
      { word: 'bonnet', emoji: '👒', emojis: ['👒', '👗'] },
      { word: 'bottle', emoji: '🍼', emojis: ['🍼', '🫙', '💧'] },
      { word: 'bounce', emoji: '⚽', emojis: ['⚽', '🏀', '🎈'] },
      { word: 'bundle', emoji: '🎁', emojis: ['🎁', '📦'] },
      { word: 'carpet', emoji: '🪑', emojis: ['🪑', '🏠', '🧶'] },
      { word: 'carrot', emoji: '🥕', emojis: ['🥕', '🐰'] },
      { word: 'cobble', emoji: '🪨', emojis: ['🪨', '🏰'] },
      { word: 'cuckoo', emoji: '🕰️', emojis: ['🕰️', '🐦'] },
      { word: 'donkey', emoji: '🫏', emojis: ['🫏', '🐴'] },
      { word: 'dragon', emoji: '🐉', emojis: ['🐉', '🔥', '🦎'] },
      { word: 'fiddle', emoji: '🎻', emojis: ['🎻', '🎵'] },
      { word: 'goblet', emoji: '🏆', emojis: ['🏆', '🍷'] },
      { word: 'jester', emoji: '🃏', emojis: ['🃏', '🤡', '🎭'] },
      { word: 'knight', emoji: '♟️', emojis: ['♟️', '⚔️', '🛡️'] },
      { word: 'kernel', emoji: '🌽', emojis: ['🌽', '🌰', '🌾'] },
    ],
  },
  {
    name: 'space',
    emoji: '🚀',
    words: [
      { word: 'galaxy', emoji: '🌌', emojis: ['🌌', '✨', '🔭'] },
      { word: 'nebula', emoji: '🌌', emojis: ['🌌', '🌈', '✨'] },
      { word: 'saturn', emoji: '🪐', emojis: ['🪐', '⭕'] },
      { word: 'cosmic', emoji: '🌌', emojis: ['🌌', '✨', '🔭'] },
      { word: 'meteor', emoji: '☄️', emojis: ['☄️', '🌠', '🪨'] },
      { word: 'starry', emoji: '🌟', emojis: ['🌟', '✨', '🌌'] },
      { word: 'bright', emoji: '✨', emojis: ['✨', '💡', '☀️', '🌟'] },
      { word: 'silent', emoji: '🌌', emojis: ['🌌', '🤫', '🔕'] },
      { word: 'wonder', emoji: '🌟', emojis: ['🌟', '😮', '✨'] },
      { word: 'silver', emoji: '⭐', emojis: ['⭐', '🥈', '🌕'] },
      { word: 'kitten', emoji: '🐱', emojis: ['🐱', '😸', '🐈'] },
      { word: 'ladder', emoji: '🪜', emojis: ['🪜', '📶'] },
      { word: 'monkey', emoji: '🐒', emojis: ['🐒', '🐵'] },
      { word: 'doctor', emoji: '👩‍⚕️', emojis: ['👩‍⚕️', '💉', '🩺'] },
      { word: 'purple', emoji: '💜', emojis: ['💜', '🔮', '🍇'] },
      { word: 'pretty', emoji: '🌸', emojis: ['🌸', '✨', '💐'] },
      { word: 'button', emoji: '🔘', emojis: ['🔘', '🪡'] },
      { word: 'circle', emoji: '⭕', emojis: ['⭕', '🔵', '⚽', '🌕'] },
      { word: 'mirror', emoji: '🪞', emojis: ['🪞', '💎'] },
      { word: 'spider', emoji: '🕷️', emojis: ['🕷️', '🕸️'] },
      { word: 'parrot', emoji: '🦜', emojis: ['🦜', '🐦'] },
      { word: 'forest', emoji: '🌲', emojis: ['🌲', '🌳', '🌿'] },
      { word: 'friend', emoji: '🤝', emojis: ['🤝', '🫂', '😊'] },
      { word: 'ribbon', emoji: '🎀', emojis: ['🎀', '🎗️'] },
      { word: 'spring', emoji: '🌱', emojis: ['🌱', '🌸', '🌤️'] },
      { word: 'sleepy', emoji: '😴', emojis: ['😴', '🌙', '🛏️'] },
      { word: 'soccer', emoji: '⚽', emojis: ['⚽', '🥅', '👟'] },
      { word: 'smooth', emoji: '🌊', emojis: ['🌊', '🪨', '💎'] },
      { word: 'locket', emoji: '❤️', emojis: ['❤️', '🔑', '📿'] },
      { word: 'orange', emoji: '🍊', emojis: ['🍊', '🟠'] },
      { word: 'accent', emoji: '🎵', emojis: ['🎵', '💬'] },
      { word: 'alpine', emoji: '⛷️', emojis: ['⛷️', '🏔️', '❄️'] },
      { word: 'always', emoji: '♾️', emojis: ['♾️', '⏱️'] },
      { word: 'barrel', emoji: '🛢️', emojis: ['🛢️', '🍺'] },
      { word: 'before', emoji: '⏮️', emojis: ['⏮️', '⏰'] },
      { word: 'belong', emoji: '🏠', emojis: ['🏠', '🧩'] },
      { word: 'beside', emoji: '↔️', emojis: ['↔️', '🤝'] },
      { word: 'better', emoji: '⬆️', emojis: ['⬆️', '✅', '🌟'] },
      { word: 'bitter', emoji: '😬', emojis: ['😬', '🍋', '☕'] },
      { word: 'clever', emoji: '🧠', emojis: ['🧠', '🦊', '💡'] },
      { word: 'dagger', emoji: '🗡️', emojis: ['🗡️', '⚔️'] },
      { word: 'falcon', emoji: '🦅', emojis: ['🦅', '🐦'] },
      { word: 'gallop', emoji: '🐴', emojis: ['🐴', '🏇'] },
      { word: 'harbor', emoji: '⚓', emojis: ['⚓', '⛵', '🌊'] },
      { word: 'hustle', emoji: '🏃', emojis: ['🏃', '💪', '⚡'] },
      { word: 'jackal', emoji: '🦊', emojis: ['🦊', '🐺'] },
      { word: 'lather', emoji: '🧼', emojis: ['🧼', '🫧', '🚿'] },
      { word: 'magnet', emoji: '🧲', emojis: ['🧲', '💫'] },
      { word: 'mellow', emoji: '😌', emojis: ['😌', '🎵', '🍂'] },
      { word: 'nimble', emoji: '🤸', emojis: ['🤸', '🐿️', '🦊'] },
    ],
  },
  {
    name: 'aurora',
    emoji: '🌌',
    words: [
      { word: 'aurora', emoji: '🌌', emojis: ['🌌', '🌈', '✨'] },
      { word: 'arctic', emoji: '🧊', emojis: ['🧊', '❄️', '🐻‍❄️'] },
      { word: 'tundra', emoji: '🌨️', emojis: ['🌨️', '❄️', '🏔️'] },
      { word: 'purple', emoji: '💜', emojis: ['💜', '🍇', '🔮'] },
      { word: 'frozen', emoji: '❄️', emojis: ['❄️', '🧊', '🥶'] },
      { word: 'starry', emoji: '🌟', emojis: ['🌟', '✨', '🌌'] },
      { word: 'ribbon', emoji: '🎀', emojis: ['🎀', '🌈', '🎗️'] },
      { word: 'marvel', emoji: '✨', emojis: ['✨', '😮', '🌟'] },
      { word: 'wonder', emoji: '🌟', emojis: ['🌟', '😮', '✨'] },
      { word: 'shimmy', emoji: '💃', emojis: ['💃', '✨', '🎵'] },
      { word: 'ripple', emoji: '🌊', emojis: ['🌊', '💧', '🌀'] },
      { word: 'gentle', emoji: '🕊️', emojis: ['🕊️', '🌸', '😊'] },
      { word: 'stream', emoji: '🌊', emojis: ['🌊', '💧', '🏞️'] },
      { word: 'lights', emoji: '💡', emojis: ['💡', '✨', '🌟', '🔦'] },
      { word: 'colors', emoji: '🌈', emojis: ['🌈', '🎨', '✨'] },
      { word: 'dancer', emoji: '💃', emojis: ['💃', '🕺'] },
      { word: 'spiral', emoji: '🌀', emojis: ['🌀', '🐚', '🌌'] },
      { word: 'velvet', emoji: '🖤', emojis: ['🖤', '🟣', '🌹'] },
      { word: 'cobalt', emoji: '🔵', emojis: ['🔵', '🌊', '💙'] },
      { word: 'canopy', emoji: '🌿', emojis: ['🌿', '🌳', '☂️'] },
      { word: 'frosty', emoji: '❄️', emojis: ['❄️', '⛄', '🥶'] },
      { word: 'winter', emoji: '☃️', emojis: ['☃️', '❄️', '🌨️'] },
      { word: 'shadow', emoji: '🌑', emojis: ['🌑', '🌘', '😶‍🌫️'] },
      { word: 'spirit', emoji: '👻', emojis: ['👻', '🕊️', '✨'] },
      { word: 'mystic', emoji: '🔮', emojis: ['🔮', '✨', '🌌'] },
      { word: 'signal', emoji: '📡', emojis: ['📡', '📶', '⚡'] },
      { word: 'copper', emoji: '🟤', emojis: ['🟤', '🪙', '🔶'] },
      { word: 'golden', emoji: '🌟', emojis: ['🌟', '🥇', '🌕', '🍯'] },
      { word: 'indigo', emoji: '🔷', emojis: ['🔷', '💙', '🔵'] },
      { word: 'radial', emoji: '✨', emojis: ['✨', '🌟', '☀️'] },
      { word: 'breeze', emoji: '💨', emojis: ['💨', '🌬️', '🍃'] },
      { word: 'dapper', emoji: '🎩', emojis: ['🎩', '✨', '👔'] },
      { word: 'darken', emoji: '🌑', emojis: ['🌑', '🌘', '🕯️'] },
      { word: 'dazzle', emoji: '✨', emojis: ['✨', '🌟', '💎'] },
      { word: 'dreamy', emoji: '😴', emojis: ['😴', '✨', '🌙'] },
      { word: 'driven', emoji: '💪', emojis: ['💪', '🏃', '🎯'] },
      { word: 'frolic', emoji: '🐑', emojis: ['🐑', '😄', '🐇'] },
      { word: 'gifted', emoji: '🎁', emojis: ['🎁', '✨', '🌟'] },
      { word: 'glassy', emoji: '💎', emojis: ['💎', '🌊', '🪟'] },
      { word: 'gravel', emoji: '🪨', emojis: ['🪨', '🛤️'] },
      { word: 'grotto', emoji: '🕳️', emojis: ['🕳️', '🦇', '🌿'] },
      { word: 'huddle', emoji: '🤗', emojis: ['🤗', '🫂', '🐧'] },
      { word: 'kindle', emoji: '🔥', emojis: ['🔥', '🕯️', '📚'] },
      { word: 'luster', emoji: '✨', emojis: ['✨', '💎', '🌟'] },
      { word: 'mellow', emoji: '😌', emojis: ['😌', '🍂', '🎵'] },
      { word: 'mortal', emoji: '⏳', emojis: ['⏳', '❤️'] },
      { word: 'nestle', emoji: '🤗', emojis: ['🤗', '🐦', '🌿'] },
      { word: 'postal', emoji: '📮', emojis: ['📮', '✉️'] },
      { word: 'rattle', emoji: '🎵', emojis: ['🎵', '🐍', '🍼'] },
      { word: 'rustle', emoji: '🍃', emojis: ['🍃', '💨', '🌿'] },
    ],
  },
  // ── 7-letter words ──────────────────────────────────────────────────────────
  {
    name: 'skyscraper',
    emoji: '🏙️',
    words: [
      { word: 'dolphin', emoji: '🐬' },
      { word: 'chicken', emoji: '🐔', emojis: ['🐔', '🐓', '🍗'] },
      { word: 'blanket', emoji: '🛏️', emojis: ['🛏️', '🧶', '😴'] },
      { word: 'captain', emoji: '⚓', emojis: ['⚓', '🧑‍✈️', '⛵'] },
      { word: 'diamond', emoji: '💎', emojis: ['💎', '💍', '🔷'] },
      { word: 'firefly', emoji: '✨', emojis: ['✨', '🌟', '🔦'] },
      { word: 'giraffe', emoji: '🦒' },
      { word: 'popcorn', emoji: '🍿' },
      { word: 'rainbow', emoji: '🌈', emojis: ['🌈', '☀️', '🌦️'] },
      { word: 'sparrow', emoji: '🐦', emojis: ['🐦', '🕊️'] },
      { word: 'unicorn', emoji: '🦄', emojis: ['🦄', '✨'] },
      { word: 'monster', emoji: '👹', emojis: ['👹', '👾', '🦖'] },
      { word: 'feather', emoji: '🪶', emojis: ['🪶', '🐦', '✉️'] },
      { word: 'brother', emoji: '👦', emojis: ['👦', '👨‍👦'] },
      { word: 'teacher', emoji: '👩‍🏫', emojis: ['👩‍🏫', '📚', '✏️'] },
      { word: 'thunder', emoji: '⛈️', emojis: ['⛈️', '⚡', '🌩️'] },
      { word: 'kitchen', emoji: '🍳', emojis: ['🍳', '🥘', '🫕'] },
      { word: 'penguin', emoji: '🐧' },
      { word: 'lantern', emoji: '🏮', emojis: ['🏮', '🕯️', '🔦'] },
      { word: 'mystery', emoji: '🔍', emojis: ['🔍', '🕵️', '❓'] },
      { word: 'present', emoji: '🎁', emojis: ['🎁', '🎀', '📦'] },
      { word: 'history', emoji: '📚', emojis: ['📚', '🏛️', '📜'] },
      { word: 'morning', emoji: '🌅', emojis: ['🌅', '☀️', '☕'] },
      { word: 'country', emoji: '🌍', emojis: ['🌍', '🗺️', '🏡'] },
      { word: 'flowers', emoji: '🌸', emojis: ['🌸', '💐', '🌺'] },
      { word: 'animals', emoji: '🦁', emojis: ['🦁', '🐘', '🐒', '🦊'] },
      { word: 'balloon', emoji: '🎈', emojis: ['🎈', '🎉', '🎪'] },
      { word: 'chimney', emoji: '🏠', emojis: ['🏠', '💨', '🔥'] },
      { word: 'curtain', emoji: '🪟', emojis: ['🪟', '🎭'] },
      { word: 'village', emoji: '🏘️', emojis: ['🏘️', '🌄', '🏡'] },
      { word: 'alright', emoji: '✅', emojis: ['✅', '👍', '😊'] },
      { word: 'cabinet', emoji: '🗄️', emojis: ['🗄️', '🏠'] },
      { word: 'carried', emoji: '💪', emojis: ['💪', '🎒'] },
      { word: 'cricket', emoji: '🏏', emojis: ['🏏', '🦗'] },
      { word: 'crowded', emoji: '👥', emojis: ['👥', '🏙️'] },
      { word: 'dazzled', emoji: '😍', emojis: ['😍', '✨', '🌟'] },
      { word: 'dormant', emoji: '😴', emojis: ['😴', '🌋', '🐻'] },
      { word: 'express', emoji: '🚄', emojis: ['🚄', '⚡', '✉️'] },
      { word: 'fantasy', emoji: '🔮', emojis: ['🔮', '🧙', '🌈'] },
      { word: 'fighter', emoji: '🥊', emojis: ['🥊', '⚔️', '✈️'] },
      { word: 'filling', emoji: '🍩', emojis: ['🍩', '🥧', '🍰'] },
      { word: 'flutter', emoji: '🦋', emojis: ['🦋', '💨', '🐦'] },
      { word: 'freckle', emoji: '😊', emojis: ['😊', '☀️'] },
      { word: 'habitat', emoji: '🌿', emojis: ['🌿', '🏠', '🦁'] },
      { word: 'imagine', emoji: '💭', emojis: ['💭', '✨', '🌈'] },
      { word: 'knitted', emoji: '🧶', emojis: ['🧶', '🧣'] },
      { word: 'leaping', emoji: '🐸', emojis: ['🐸', '🦘', '🏃'] },
      { word: 'lobster', emoji: '🦞', emojis: ['🦞', '🦀'] },
      { word: 'marshal', emoji: '⭐', emojis: ['⭐', '🏛️', '🤠'] },
      { word: 'lanyard', emoji: '🪪', emojis: ['🪪', '🔑', '📿'] },
    ],
  },
  {
    name: 'tornado',
    emoji: '🌪️',
    words: [
      { word: 'tornado', emoji: '🌪️' },
      { word: 'cyclone', emoji: '🌀', emojis: ['🌀', '🌪️'] },
      { word: 'twister', emoji: '🌪️', emojis: ['🌪️', '🌀'] },
      { word: 'thunder', emoji: '⛈️', emojis: ['⛈️', '⚡', '🌩️'] },
      { word: 'weather', emoji: '🌤️', emojis: ['🌤️', '⛈️', '🌈'] },
      { word: 'shelter', emoji: '🏠', emojis: ['🏠', '⛺', '🛖'] },
      { word: 'warning', emoji: '⚠️', emojis: ['⚠️', '🚨', '🔔'] },
      { word: 'howling', emoji: '🐺', emojis: ['🐺', '🌕', '💨'] },
      { word: 'roaring', emoji: '🦁', emojis: ['🦁', '🌊', '🔊'] },
      { word: 'rushing', emoji: '💨', emojis: ['💨', '🌊', '🏃'] },
      { word: 'swirled', emoji: '🌀', emojis: ['🌀', '💨', '🌪️'] },
      { word: 'sunbeam', emoji: '☀️', emojis: ['☀️', '🌅', '🔦'] },
      { word: 'bluster', emoji: '💨', emojis: ['💨', '🌬️', '😤'] },
      { word: 'gushing', emoji: '💦', emojis: ['💦', '🌊', '💧'] },
      { word: 'whipped', emoji: '💨', emojis: ['💨', '🍦', '🌪️'] },
      { word: 'churned', emoji: '🌊', emojis: ['🌊', '🌀'] },
      { word: 'billows', emoji: '☁️', emojis: ['☁️', '🌊', '💨'] },
      { word: 'smashed', emoji: '💥', emojis: ['💥', '🔨'] },
      { word: 'rainbow', emoji: '🌈', emojis: ['🌈', '🌦️', '☀️'] },
      { word: 'windows', emoji: '🪟', emojis: ['🪟', '🏠'] },
      { word: 'rooftop', emoji: '🏠', emojis: ['🏠', '🌧️', '🐦'] },
      { word: 'puddles', emoji: '💧', emojis: ['💧', '🌧️', '👟'] },
      { word: 'drizzle', emoji: '🌧️', emojis: ['🌧️', '💧', '☔'] },
      { word: 'crackle', emoji: '⚡', emojis: ['⚡', '🔥', '🌩️'] },
      { word: 'scatter', emoji: '🍂', emojis: ['🍂', '💨', '🌪️'] },
      { word: 'caravan', emoji: '🚐', emojis: ['🚐', '🏕️'] },
      { word: 'outside', emoji: '🏞️', emojis: ['🏞️', '🌳', '☀️'] },
      { word: 'cottage', emoji: '🏡', emojis: ['🏡', '🌸', '🌲'] },
      { word: 'sparkle', emoji: '✨', emojis: ['✨', '💎', '🌟'] },
      { word: 'twirled', emoji: '💃', emojis: ['💃', '🌀', '🌪️'] },
      { word: 'boulder', emoji: '🪨', emojis: ['🪨', '⛰️', '💪'] },
      { word: 'camping', emoji: '🏕️', emojis: ['🏕️', '🔥', '🌲'] },
      { word: 'ceiling', emoji: '🏠', emojis: ['🏠', '🎨'] },
      { word: 'clatter', emoji: '💥', emojis: ['💥', '🍽️', '🔔'] },
      { word: 'cluster', emoji: '🍇', emojis: ['🍇', '⭐', '👥'] },
      { word: 'comfort', emoji: '🛋️', emojis: ['🛋️', '🤗', '☕'] },
      { word: 'compass', emoji: '🧭', emojis: ['🧭', '📍'] },
      { word: 'concert', emoji: '🎵', emojis: ['🎵', '🎤', '🎸'] },
      { word: 'costume', emoji: '🎭', emojis: ['🎭', '👗', '🎪'] },
      { word: 'counter', emoji: '🔢', emojis: ['🔢', '🧾', '🏪'] },
      { word: 'curious', emoji: '🔍', emojis: ['🔍', '🦊', '❓'] },
      { word: 'devoted', emoji: '❤️', emojis: ['❤️', '🫶', '💪'] },
      { word: 'digital', emoji: '💻', emojis: ['💻', '📱', '⌨️'] },
      { word: 'display', emoji: '🖥️', emojis: ['🖥️', '📺', '🎨'] },
      { word: 'dribble', emoji: '🏀', emojis: ['🏀', '💧', '⚽'] },
      { word: 'elderly', emoji: '👴', emojis: ['👴', '👵'] },
      { word: 'episode', emoji: '📺', emojis: ['📺', '🎬', '🎭'] },
      { word: 'example', emoji: '📋', emojis: ['📋', '📝', '🏫'] },
      { word: 'excited', emoji: '🎉', emojis: ['🎉', '😄', '⚡'] },
      { word: 'explore', emoji: '🔍', emojis: ['🔍', '🗺️', '🧭'] },
    ],
  },
  {
    name: 'glacier',
    emoji: '🧊',
    words: [
      { word: 'glacier', emoji: '🧊', emojis: ['🧊', '❄️', '🏔️'] },
      { word: 'iceberg', emoji: '🧊', emojis: ['🧊', '🚢', '❄️'] },
      { word: 'crystal', emoji: '💎', emojis: ['💎', '❄️', '✨'] },
      { word: 'frosted', emoji: '❄️', emojis: ['❄️', '🥶', '🍩'] },
      { word: 'snowcap', emoji: '🏔️', emojis: ['🏔️', '❄️', '⛄'] },
      { word: 'flowing', emoji: '🌊', emojis: ['🌊', '💧', '🏞️'] },
      { word: 'ancient', emoji: '🗿', emojis: ['🗿', '📜', '⏳'] },
      { word: 'beneath', emoji: '⬇️', emojis: ['⬇️', '🌊', '🕳️'] },
      { word: 'endless', emoji: '♾️', emojis: ['♾️', '🌌', '🌊'] },
      { word: 'shimmer', emoji: '✨', emojis: ['✨', '💫', '🌟'] },
      { word: 'glisten', emoji: '💧', emojis: ['💧', '✨', '🌟'] },
      { word: 'silence', emoji: '🤫', emojis: ['🤫', '🌌', '🔕'] },
      { word: 'journey', emoji: '🗺️', emojis: ['🗺️', '🚀', '🚶'] },
      { word: 'pathway', emoji: '🛤️', emojis: ['🛤️', '🗺️', '👣'] },
      { word: 'explore', emoji: '🔍', emojis: ['🔍', '🗺️', '🧭'] },
      { word: 'breathe', emoji: '💨', emojis: ['💨', '🫁', '🌿'] },
      { word: 'crevice', emoji: '🕳️', emojis: ['🕳️', '🪨', '❄️'] },
      { word: 'distant', emoji: '🌅', emojis: ['🌅', '🔭', '🌄'] },
      { word: 'melting', emoji: '💧', emojis: ['💧', '❄️', '☀️'] },
      { word: 'glowing', emoji: '🌟', emojis: ['🌟', '✨', '🕯️'] },
      { word: 'dazzled', emoji: '😍', emojis: ['😍', '✨', '🌟'] },
      { word: 'clarity', emoji: '🔭', emojis: ['🔭', '💎', '✨'] },
      { word: 'freedom', emoji: '🦅', emojis: ['🦅', '🕊️', '🌈'] },
      { word: 'sunrise', emoji: '🌅', emojis: ['🌅', '☀️', '🌄'] },
      { word: 'shining', emoji: '✨', emojis: ['✨', '☀️', '💎'] },
      { word: 'coldest', emoji: '🥶', emojis: ['🥶', '❄️', '🧊'] },
      { word: 'heights', emoji: '⛰️', emojis: ['⛰️', '🏔️', '🦅'] },
      { word: 'forever', emoji: '♾️', emojis: ['♾️', '❤️', '⏳'] },
      { word: 'mystery', emoji: '🔍', emojis: ['🔍', '🕵️', '❓'] },
      { word: 'horizon', emoji: '🌄', emojis: ['🌄', '🌅', '🔭'] },
      { word: 'another', emoji: '➕', emojis: ['➕', '🔄', '👥'] },
      { word: 'athlete', emoji: '🏅', emojis: ['🏅', '🏃', '💪'] },
      { word: 'bicycle', emoji: '🚲', emojis: ['🚲', '🚴', '🛞'] },
      { word: 'blossom', emoji: '🌸', emojis: ['🌸', '🌺', '🌻'] },
      { word: 'brought', emoji: '🎁', emojis: ['🎁', '💪', '🛒'] },
      { word: 'calling', emoji: '📞', emojis: ['📞', '📢', '🎵'] },
      { word: 'careful', emoji: '🦺', emojis: ['🦺', '⚠️', '🧠'] },
      { word: 'citizen', emoji: '🏛️', emojis: ['🏛️', '🗳️', '🌍'] },
      { word: 'collect', emoji: '🗂️', emojis: ['🗂️', '🧺', '🎨'] },
      { word: 'cooking', emoji: '🍳', emojis: ['🍳', '👨‍🍳', '🔥'] },
      { word: 'covered', emoji: '🌂', emojis: ['🌂', '🏠', '❄️'] },
      { word: 'cracker', emoji: '🍘', emojis: ['🍘', '🎄', '🧀'] },
      { word: 'created', emoji: '🎨', emojis: ['🎨', '✨', '🏗️'] },
      { word: 'culture', emoji: '🎭', emojis: ['🎭', '🌍', '🎨'] },
      { word: 'current', emoji: '🌊', emojis: ['🌊', '⚡', '💨'] },
      { word: 'dancing', emoji: '💃', emojis: ['💃', '🕺', '🎵'] },
      { word: 'deliver', emoji: '📦', emojis: ['📦', '🚚', '📮'] },
      { word: 'deposit', emoji: '🏦', emojis: ['🏦', '💰'] },
      { word: 'deserve', emoji: '🏆', emojis: ['🏆', '⭐', '🌟'] },
      { word: 'devoted', emoji: '❤️', emojis: ['❤️', '🫶', '💪'] },
    ],
  },
];

const AVATARS = ['🦊', '🐱', '🐶', '🐸', '🐼', '🦄'];
const DEFAULT_AVATARS = ['🦊', '🐱', '🐶', '🐸'];
const PLAYER_COLORS = { 1: '#ff4d4d', 2: '#4d94ff', 3: '#4dff88', 4: '#ffcc4d' };
const ALLOWED_COLORS = new Set(['#ff4d4d', '#4d94ff', '#4dff88', '#ffcc4d', '#cc4dff', '#ff8c4d']);

export const WORDS_PER_OBSTACLE = 30;

function makePlayer(id) {
  return {
    id,
    connected: false,
    paused: false,
    avatar: DEFAULT_AVATARS[id - 1] ?? '🦊',
    color: PLAYER_COLORS[id] ?? '#ffffff',
  };
}

function shuffle(arr) {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

function makeWordOrder(count) {
  return shuffle([...Array(count).keys()]);
}

function pickEmoji(wordEntry) {
  if (Math.random() < 0.2) return '';
  const pool = wordEntry.emojis ?? [wordEntry.emoji];
  return pool[Math.floor(Math.random() * pool.length)];
}

export function newGameState() {
  const obstacle = OBSTACLES[0];
  const wordOrder = makeWordOrder(obstacle.words.length);
  const firstWord = obstacle.words[wordOrder[0]];
  return {
    tick: 0,
    paused: true,
    reasonPaused: 'start',
    obstacleIndex: 0,
    wordIndex: 0,
    wordOrder,
    letterIndex: 0,
    wordsCompleted: 0,
    wordsPerObstacle: WORDS_PER_OBSTACLE,
    currentWord: firstWord.word,
    currentEmoji: pickEmoji(firstWord),
    obstacleName: obstacle.name,
    obstacleEmoji: obstacle.emoji,
    recentWords: [],
    celebrating: false,
    celebrateStart: 0,
    lastTypedBy: null,
    players: {
      1: makePlayer(1),
      2: makePlayer(2),
      3: makePlayer(3),
      4: makePlayer(4),
    },
  };
}

export function setPlayerConnected(state, playerId, connected) {
  const p = state.players[playerId];
  if (p) p.connected = connected;
}

export function resumeGame(state, playerId) {
  if (!playerId) return;
  const p = state.players[playerId];
  if (p) p.paused = false;
  if (state.paused) {
    state.paused = false;
    state.reasonPaused = null;
  }
}

export function togglePause(state, playerId) {
  if (!playerId) return;
  if (state.paused && state.reasonPaused === 'start') {
    state.paused = false;
    state.reasonPaused = null;
  } else if (!state.paused) {
    state.paused = true;
    state.reasonPaused = 'paused';
  } else {
    state.paused = false;
    state.reasonPaused = null;
  }
}

export function selectAvatar(state, playerId, avatar) {
  const p = state.players[playerId];
  if (!p) return;
  if (AVATARS.includes(avatar)) p.avatar = avatar;
}

export function selectColor(state, playerId, color) {
  const p = state.players[playerId];
  if (!p) return;
  const c = String(color ?? '').toLowerCase();
  if (ALLOWED_COLORS.has(c)) p.color = c;
}

export function applyKey(state, playerId, key) {
  if (state.paused) return;
  if (state.celebrating) return;

  const k = String(key ?? '').toLowerCase();
  if (k.length !== 1 || !/[a-z]/.test(k)) return;
  if (k !== state.currentWord[state.letterIndex]) return;

  state.letterIndex++;
  state.lastTypedBy = playerId;

  if (state.letterIndex >= state.currentWord.length) {
    const done = { word: state.currentWord, emoji: state.currentEmoji };
    state.recentWords = [done, ...state.recentWords].slice(0, 6);
    state.wordsCompleted++;

    if (state.wordsCompleted >= state.wordsPerObstacle) {
      state.celebrating = true;
      state.celebrateStart = Date.now();
      state.letterIndex = 0;
    } else {
      state.wordIndex++;
      state.letterIndex = 0;
      const words = OBSTACLES[state.obstacleIndex].words;
      const rawIndex = state.wordOrder ? state.wordOrder[state.wordIndex] : state.wordIndex;
      const next = words[rawIndex];
      state.currentWord = next.word;
      state.currentEmoji = pickEmoji(next);
    }
  }
}

function loadObstacle(state, obstacleIndex) {
  const obstacle = OBSTACLES[obstacleIndex];
  const wordOrder = makeWordOrder(obstacle.words.length);
  const firstWord = obstacle.words[wordOrder[0]];
  state.obstacleIndex = obstacleIndex;
  state.wordOrder = wordOrder;
  state.wordIndex = 0;
  state.letterIndex = 0;
  state.wordsCompleted = 0;
  state.recentWords = [];
  state.celebrating = false;
  state.celebrateStart = 0;
  state.lastTypedBy = null;
  state.currentWord = firstWord.word;
  state.currentEmoji = pickEmoji(firstWord);
  state.obstacleName = obstacle.name;
  state.obstacleEmoji = obstacle.emoji;
}

export function nextObstacle(state) {
  if (!state.celebrating) return;
  const nextIdx = (state.obstacleIndex + 1) % OBSTACLES.length;
  loadObstacle(state, nextIdx);
  // no pause — game starts immediately after celebration
}

export function restart(state) {
  loadObstacle(state, state.obstacleIndex);
}

export function selectObstacle(state, index) {
  const idx = Math.max(0, Math.min(OBSTACLES.length - 1, index));
  loadObstacle(state, idx);
  state.paused = true;
  state.reasonPaused = 'start';
}

export function step(state, _now) {
  state.tick++;
}
